/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAssistantRouteImport } from './routes/admin/assistant'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTelemetryRouteImport } from './routes/admin/telemetry'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerApplicationsRouteImport } from './routes/customer/applications'
import { Route as CustomerAssistantRouteImport } from './routes/customer/assistant'
import { Route as CustomerHelpRouteImport } from './routes/customer/help'
import { Route as CustomerNotificationsRouteImport } from './routes/customer/notifications'
import { Route as CustomerSettingsRouteImport } from './routes/customer/settings'
import { Route as CustomerVaultRouteImport } from './routes/customer/vault'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as EmployeeAiToolsRouteImport } from './routes/employee/ai-tools'
import { Route as EmployeeApplicationsRouteImport } from './routes/employee/applications'
import { Route as EmployeeAssistantRouteImport } from './routes/employee/assistant'
import { Route as EmployeeCustomersRouteImport } from './routes/employee/customers'
import { Route as EmployeeDocumentsRouteImport } from './routes/employee/documents'
import { Route as EmployeeKycRouteImport } from './routes/employee/kyc'
import { Route as EmployeeNotificationsRouteImport } from './routes/employee/notifications'
import { Route as EmployeeRiskRouteImport } from './routes/employee/risk'
import { Route as Login2faRouteImport } from './routes/login/2fa'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as LoginCustomerRouteImport } from './routes/login/customer'
import { Route as LoginEmployeeRouteImport } from './routes/login/employee'
import { Route as LoginManagerRouteImport } from './routes/login/manager'
import { Route as LoginRoleSelectRouteImport } from './routes/login/role-select'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as ManagerAiToolsRouteImport } from './routes/manager/ai-tools'
import { Route as ManagerAnalyticsRouteImport } from './routes/manager/analytics'
import { Route as ManagerApprovalsRouteImport } from './routes/manager/approvals'
import { Route as ManagerAssistantRouteImport } from './routes/manager/assistant'
import { Route as ManagerAuditLogsRouteImport } from './routes/manager/audit-logs'
import { Route as ManagerCustomersRouteImport } from './routes/manager/customers'
import { Route as ManagerRiskRouteImport } from './routes/manager/risk'
import { Route as ManagerSettingsRouteImport } from './routes/manager/settings'
import { Route as ManagerUsersRouteImport } from './routes/manager/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/admin/assistant',
  path: '/admin/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTelemetryRoute = AdminTelemetryRouteImport.update({
  id: '/admin/telemetry',
  path: '/admin/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerApplicationsRoute = CustomerApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAssistantRoute = CustomerAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerHelpRoute = CustomerHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSettingsRoute = CustomerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerVaultRoute = CustomerVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => CustomerRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAiToolsRoute = EmployeeAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeApplicationsRoute = EmployeeApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAssistantRoute = EmployeeAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeCustomersRoute = EmployeeCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeDocumentsRoute = EmployeeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeKycRoute = EmployeeKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeNotificationsRoute = EmployeeNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeRiskRoute = EmployeeRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => EmployeeRoute,
} as any)
const Login2faRoute = Login2faRouteImport.update({
  id: '/login/2fa',
  path: '/login/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCustomerRoute = LoginCustomerRouteImport.update({
  id: '/login/customer',
  path: '/login/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmployeeRoute = LoginEmployeeRouteImport.update({
  id: '/login/employee',
  path: '/login/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginManagerRoute = LoginManagerRouteImport.update({
  id: '/login/manager',
  path: '/login/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoleSelectRoute = LoginRoleSelectRouteImport.update({
  id: '/login/role-select',
  path: '/login/role-select',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAiToolsRoute = ManagerAiToolsRouteImport.update({
  id: '/ai-tools',
  path: '/ai-tools',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerApprovalsRoute = ManagerApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAssistantRoute = ManagerAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAuditLogsRoute = ManagerAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerCustomersRoute = ManagerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerRiskRoute = ManagerRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerUsersRoute = ManagerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/applications': typeof CustomerApplicationsRoute
  '/customer/assistant': typeof CustomerAssistantRoute
  '/customer/help': typeof CustomerHelpRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/vault': typeof CustomerVaultRoute
  '/employee/ai-tools': typeof EmployeeAiToolsRoute
  '/employee/applications': typeof EmployeeApplicationsRoute
  '/employee/assistant': typeof EmployeeAssistantRoute
  '/employee/customers': typeof EmployeeCustomersRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/kyc': typeof EmployeeKycRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/risk': typeof EmployeeRiskRoute
  '/login/2fa': typeof Login2faRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/login/manager': typeof LoginManagerRoute
  '/login/role-select': typeof LoginRoleSelectRoute
  '/manager/ai-tools': typeof ManagerAiToolsRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/assistant': typeof ManagerAssistantRoute
  '/manager/audit-logs': typeof ManagerAuditLogsRoute
  '/manager/customers': typeof ManagerCustomersRoute
  '/manager/risk': typeof ManagerRiskRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/applications': typeof CustomerApplicationsRoute
  '/customer/assistant': typeof CustomerAssistantRoute
  '/customer/help': typeof CustomerHelpRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/vault': typeof CustomerVaultRoute
  '/employee/ai-tools': typeof EmployeeAiToolsRoute
  '/employee/applications': typeof EmployeeApplicationsRoute
  '/employee/assistant': typeof EmployeeAssistantRoute
  '/employee/customers': typeof EmployeeCustomersRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/kyc': typeof EmployeeKycRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/risk': typeof EmployeeRiskRoute
  '/login/2fa': typeof Login2faRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/login/manager': typeof LoginManagerRoute
  '/login/role-select': typeof LoginRoleSelectRoute
  '/manager/ai-tools': typeof ManagerAiToolsRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/assistant': typeof ManagerAssistantRoute
  '/manager/audit-logs': typeof ManagerAuditLogsRoute
  '/manager/customers': typeof ManagerCustomersRoute
  '/manager/risk': typeof ManagerRiskRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/telemetry': typeof AdminTelemetryRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/applications': typeof CustomerApplicationsRoute
  '/customer/assistant': typeof CustomerAssistantRoute
  '/customer/help': typeof CustomerHelpRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/vault': typeof CustomerVaultRoute
  '/employee/ai-tools': typeof EmployeeAiToolsRoute
  '/employee/applications': typeof EmployeeApplicationsRoute
  '/employee/assistant': typeof EmployeeAssistantRoute
  '/employee/customers': typeof EmployeeCustomersRoute
  '/employee/documents': typeof EmployeeDocumentsRoute
  '/employee/kyc': typeof EmployeeKycRoute
  '/employee/notifications': typeof EmployeeNotificationsRoute
  '/employee/risk': typeof EmployeeRiskRoute
  '/login/2fa': typeof Login2faRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/customer': typeof LoginCustomerRoute
  '/login/employee': typeof LoginEmployeeRoute
  '/login/manager': typeof LoginManagerRoute
  '/login/role-select': typeof LoginRoleSelectRoute
  '/manager/ai-tools': typeof ManagerAiToolsRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/approvals': typeof ManagerApprovalsRoute
  '/manager/assistant': typeof ManagerAssistantRoute
  '/manager/audit-logs': typeof ManagerAuditLogsRoute
  '/manager/customers': typeof ManagerCustomersRoute
  '/manager/risk': typeof ManagerRiskRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/users': typeof ManagerUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/employee'
    | '/manager'
    | '/admin/assistant'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/admin/telemetry'
    | '/admin/users'
    | '/customer/applications'
    | '/customer/assistant'
    | '/customer/help'
    | '/customer/notifications'
    | '/customer/settings'
    | '/customer/vault'
    | '/employee/ai-tools'
    | '/employee/applications'
    | '/employee/assistant'
    | '/employee/customers'
    | '/employee/documents'
    | '/employee/kyc'
    | '/employee/notifications'
    | '/employee/risk'
    | '/login/2fa'
    | '/login/admin'
    | '/login/customer'
    | '/login/employee'
    | '/login/manager'
    | '/login/role-select'
    | '/manager/ai-tools'
    | '/manager/analytics'
    | '/manager/approvals'
    | '/manager/assistant'
    | '/manager/audit-logs'
    | '/manager/customers'
    | '/manager/risk'
    | '/manager/settings'
    | '/manager/users'
    | '/admin/'
    | '/customer/'
    | '/employee/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/assistant'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/admin/telemetry'
    | '/admin/users'
    | '/customer/applications'
    | '/customer/assistant'
    | '/customer/help'
    | '/customer/notifications'
    | '/customer/settings'
    | '/customer/vault'
    | '/employee/ai-tools'
    | '/employee/applications'
    | '/employee/assistant'
    | '/employee/customers'
    | '/employee/documents'
    | '/employee/kyc'
    | '/employee/notifications'
    | '/employee/risk'
    | '/login/2fa'
    | '/login/admin'
    | '/login/customer'
    | '/login/employee'
    | '/login/manager'
    | '/login/role-select'
    | '/manager/ai-tools'
    | '/manager/analytics'
    | '/manager/approvals'
    | '/manager/assistant'
    | '/manager/audit-logs'
    | '/manager/customers'
    | '/manager/risk'
    | '/manager/settings'
    | '/manager/users'
    | '/admin'
    | '/customer'
    | '/employee'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/employee'
    | '/manager'
    | '/admin/assistant'
    | '/admin/audit-logs'
    | '/admin/settings'
    | '/admin/telemetry'
    | '/admin/users'
    | '/customer/applications'
    | '/customer/assistant'
    | '/customer/help'
    | '/customer/notifications'
    | '/customer/settings'
    | '/customer/vault'
    | '/employee/ai-tools'
    | '/employee/applications'
    | '/employee/assistant'
    | '/employee/customers'
    | '/employee/documents'
    | '/employee/kyc'
    | '/employee/notifications'
    | '/employee/risk'
    | '/login/2fa'
    | '/login/admin'
    | '/login/customer'
    | '/login/employee'
    | '/login/manager'
    | '/login/role-select'
    | '/manager/ai-tools'
    | '/manager/analytics'
    | '/manager/approvals'
    | '/manager/assistant'
    | '/manager/audit-logs'
    | '/manager/customers'
    | '/manager/risk'
    | '/manager/settings'
    | '/manager/users'
    | '/admin/'
    | '/customer/'
    | '/employee/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  EmployeeRoute: typeof EmployeeRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTelemetryRoute: typeof AdminTelemetryRoute
  AdminUsersRoute: typeof AdminUsersRoute
  Login2faRoute: typeof Login2faRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginCustomerRoute: typeof LoginCustomerRoute
  LoginEmployeeRoute: typeof LoginEmployeeRoute
  LoginManagerRoute: typeof LoginManagerRoute
  LoginRoleSelectRoute: typeof LoginRoleSelectRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/admin/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/telemetry': {
      id: '/admin/telemetry'
      path: '/admin/telemetry'
      fullPath: '/admin/telemetry'
      preLoaderRoute: typeof AdminTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/applications': {
      id: '/customer/applications'
      path: '/applications'
      fullPath: '/customer/applications'
      preLoaderRoute: typeof CustomerApplicationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/assistant': {
      id: '/customer/assistant'
      path: '/assistant'
      fullPath: '/customer/assistant'
      preLoaderRoute: typeof CustomerAssistantRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/help': {
      id: '/customer/help'
      path: '/help'
      fullPath: '/customer/help'
      preLoaderRoute: typeof CustomerHelpRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/settings': {
      id: '/customer/settings'
      path: '/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof CustomerSettingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/vault': {
      id: '/customer/vault'
      path: '/vault'
      fullPath: '/customer/vault'
      preLoaderRoute: typeof CustomerVaultRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/ai-tools': {
      id: '/employee/ai-tools'
      path: '/ai-tools'
      fullPath: '/employee/ai-tools'
      preLoaderRoute: typeof EmployeeAiToolsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/applications': {
      id: '/employee/applications'
      path: '/applications'
      fullPath: '/employee/applications'
      preLoaderRoute: typeof EmployeeApplicationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/assistant': {
      id: '/employee/assistant'
      path: '/assistant'
      fullPath: '/employee/assistant'
      preLoaderRoute: typeof EmployeeAssistantRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/customers': {
      id: '/employee/customers'
      path: '/customers'
      fullPath: '/employee/customers'
      preLoaderRoute: typeof EmployeeCustomersRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/documents': {
      id: '/employee/documents'
      path: '/documents'
      fullPath: '/employee/documents'
      preLoaderRoute: typeof EmployeeDocumentsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/kyc': {
      id: '/employee/kyc'
      path: '/kyc'
      fullPath: '/employee/kyc'
      preLoaderRoute: typeof EmployeeKycRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/notifications': {
      id: '/employee/notifications'
      path: '/notifications'
      fullPath: '/employee/notifications'
      preLoaderRoute: typeof EmployeeNotificationsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/risk': {
      id: '/employee/risk'
      path: '/risk'
      fullPath: '/employee/risk'
      preLoaderRoute: typeof EmployeeRiskRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/login/2fa': {
      id: '/login/2fa'
      path: '/login/2fa'
      fullPath: '/login/2fa'
      preLoaderRoute: typeof Login2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/customer': {
      id: '/login/customer'
      path: '/login/customer'
      fullPath: '/login/customer'
      preLoaderRoute: typeof LoginCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/employee': {
      id: '/login/employee'
      path: '/login/employee'
      fullPath: '/login/employee'
      preLoaderRoute: typeof LoginEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/manager': {
      id: '/login/manager'
      path: '/login/manager'
      fullPath: '/login/manager'
      preLoaderRoute: typeof LoginManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/role-select': {
      id: '/login/role-select'
      path: '/login/role-select'
      fullPath: '/login/role-select'
      preLoaderRoute: typeof LoginRoleSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/ai-tools': {
      id: '/manager/ai-tools'
      path: '/ai-tools'
      fullPath: '/manager/ai-tools'
      preLoaderRoute: typeof ManagerAiToolsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/analytics': {
      id: '/manager/analytics'
      path: '/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/approvals': {
      id: '/manager/approvals'
      path: '/approvals'
      fullPath: '/manager/approvals'
      preLoaderRoute: typeof ManagerApprovalsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/assistant': {
      id: '/manager/assistant'
      path: '/assistant'
      fullPath: '/manager/assistant'
      preLoaderRoute: typeof ManagerAssistantRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/audit-logs': {
      id: '/manager/audit-logs'
      path: '/audit-logs'
      fullPath: '/manager/audit-logs'
      preLoaderRoute: typeof ManagerAuditLogsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/customers': {
      id: '/manager/customers'
      path: '/customers'
      fullPath: '/manager/customers'
      preLoaderRoute: typeof ManagerCustomersRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/risk': {
      id: '/manager/risk'
      path: '/risk'
      fullPath: '/manager/risk'
      preLoaderRoute: typeof ManagerRiskRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/users': {
      id: '/manager/users'
      path: '/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersRouteImport
      parentRoute: typeof ManagerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerApplicationsRoute: typeof CustomerApplicationsRoute
  CustomerAssistantRoute: typeof CustomerAssistantRoute
  CustomerHelpRoute: typeof CustomerHelpRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerSettingsRoute: typeof CustomerSettingsRoute
  CustomerVaultRoute: typeof CustomerVaultRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerApplicationsRoute: CustomerApplicationsRoute,
  CustomerAssistantRoute: CustomerAssistantRoute,
  CustomerHelpRoute: CustomerHelpRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerSettingsRoute: CustomerSettingsRoute,
  CustomerVaultRoute: CustomerVaultRoute,
  CustomerIndexRoute: CustomerIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface EmployeeRouteChildren {
  EmployeeAiToolsRoute: typeof EmployeeAiToolsRoute
  EmployeeApplicationsRoute: typeof EmployeeApplicationsRoute
  EmployeeAssistantRoute: typeof EmployeeAssistantRoute
  EmployeeCustomersRoute: typeof EmployeeCustomersRoute
  EmployeeDocumentsRoute: typeof EmployeeDocumentsRoute
  EmployeeKycRoute: typeof EmployeeKycRoute
  EmployeeNotificationsRoute: typeof EmployeeNotificationsRoute
  EmployeeRiskRoute: typeof EmployeeRiskRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeAiToolsRoute: EmployeeAiToolsRoute,
  EmployeeApplicationsRoute: EmployeeApplicationsRoute,
  EmployeeAssistantRoute: EmployeeAssistantRoute,
  EmployeeCustomersRoute: EmployeeCustomersRoute,
  EmployeeDocumentsRoute: EmployeeDocumentsRoute,
  EmployeeKycRoute: EmployeeKycRoute,
  EmployeeNotificationsRoute: EmployeeNotificationsRoute,
  EmployeeRiskRoute: EmployeeRiskRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface ManagerRouteChildren {
  ManagerAiToolsRoute: typeof ManagerAiToolsRoute
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRoute
  ManagerApprovalsRoute: typeof ManagerApprovalsRoute
  ManagerAssistantRoute: typeof ManagerAssistantRoute
  ManagerAuditLogsRoute: typeof ManagerAuditLogsRoute
  ManagerCustomersRoute: typeof ManagerCustomersRoute
  ManagerRiskRoute: typeof ManagerRiskRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerUsersRoute: typeof ManagerUsersRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAiToolsRoute: ManagerAiToolsRoute,
  ManagerAnalyticsRoute: ManagerAnalyticsRoute,
  ManagerApprovalsRoute: ManagerApprovalsRoute,
  ManagerAssistantRoute: ManagerAssistantRoute,
  ManagerAuditLogsRoute: ManagerAuditLogsRoute,
  ManagerCustomersRoute: ManagerCustomersRoute,
  ManagerRiskRoute: ManagerRiskRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerUsersRoute: ManagerUsersRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
  EmployeeRoute: EmployeeRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTelemetryRoute: AdminTelemetryRoute,
  AdminUsersRoute: AdminUsersRoute,
  Login2faRoute: Login2faRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginCustomerRoute: LoginCustomerRoute,
  LoginEmployeeRoute: LoginEmployeeRoute,
  LoginManagerRoute: LoginManagerRoute,
  LoginRoleSelectRoute: LoginRoleSelectRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
